sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "1234"
  alioss:
    access-key-id: LTAI5tApdpNPGpDkpDJougu9
    access-key-secret: 6p9ObIp2UohfRYLcTMLflvwCPDckHW
    bucket-name: sky-takeout--files
    endpoint: oss-cn-beijing.aliyuncs.com
  wechat:
    appid: wxd79c506fb8ab19a5
    secret: 8cd9f073cb5c2fe011c9b17443948573
  shop:
    address: 福建省南平市光泽县闽北物流伟恒锦江苑
  baidu:
    ak: VCgYZLujA75HK6L78vPaJxJQUhuBcX29
spring:
  redis:
    host: localhost
    port: 6379
    password: "1234"
    database: 0
